### ISSUE TITLE
Using pm2 to start the app

### ISSUE THREAD

**Issue by jsponz** [robertsLando/Mqtt2Mqtt#10]
I try to use pm2 to start the app, but it is not working: pm2 start app.js

<img width="632" alt="Bildschirmfoto 2020-04-08 um 06 56 22" src="https://user-images.githubusercontent.com/12778286/78746014-112cdf80-7966-11ea-8360-3d5fedd75ef3.png">

but if I start with npm start it works. 

Any hint? Thanks!

**Comment by robertsLando** [comment]
pm2 start bin/www --name m2m

**Comment by jsponz** [comment]
Thanks! It works.
