### ISSUE TITLE
Bridge mode

### ISSUE THREAD

**Issue by jsponz** [robertsLando/Mqtt2Mqtt#11]
I have a local mosquitto broker. I want to bridge it with Mqtt2Mqtt.

Do you support bridge mode? 

Thanks!

**Comment by robertsLando** [comment]
What do you mean? Mqtt2Mqtt is a mqtt bridge

**Comment by sponz** [comment]
Ok. Let me clarify the situation. 

Now, my devices connect to a MQTT cloud broker, based on Mosca. 

I want to have a local MQTT broker. I have installed it on my openWRT router. 

So I want to connect my local bridge with the cloud bridge using your Mqtt2Mqtt.

How can I do it? 

Thanks

**Comment by robertsLando** [comment]
You should configure your local bridge to publish to Mqtt2Mqtt broker and add a client to mqtt2mqtt that connects to the cloud broker based on mosca.

After this you have to configure rules to map topics between the two brokers using the UI

**Comment by sponz** [comment]
¨The part from Mqtt2Mqtt to the cloud MQTT broker is ok. 

The problem is on the configuration of the local mqtt to publish to Mqtt2Mqtt. I have tried the bridge configuration provided by mosquitto, so I bridge the local broker to Mqtt2Mqtt but it does not work. ¨

How do you suggest to make the publish from my local mqtt to Mqtt2Mqtt?

Thanks!

**Comment by robertsLando** [comment]
> I have tried the bridge configuration provided by mosquitto, so I bridge the local broker to Mqtt2Mqtt but it does not work

I don't understand why you are using mosquitto bridge mode for this. Mqtt2Mqtt inits its own broker (using Aedes MQtt broker) and you should publish to that broker directly and the rules created in the UI will bridge the incoming outgoing packets between MQtt2Mqtt broker and the cloud broker

**Comment by sponz** [comment]
I need a local MQTT broker, but I can't install your app in the local device, so I have installed it on the cloud.

**Comment by robertsLando** [comment]
YOur devices need to directly push values to Mqtt2Mqtt broker in order to make this work. You cannot have another broker locally (this means 3 brokers in total, the cloud, mosquitto and m2m broker)

**Comment by jsponz** [comment]
Ok. Thanks!
