### ISSUE TITLE
Error when saving configuration

### ISSUE THREAD

**Issue by jsponz** [robertsLando/Mqtt2Mqtt#12]
I get the following error: 

<img width="841" alt="Bildschirmfoto 2020-05-21 um 22 27 45" src="https://user-images.githubusercontent.com/12778286/82603167-77865e00-9bb2-11ea-8832-bd1f72c0b4b5.png">

when saving. 

The content of the file is as follows: 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.5
3 info using node@v10.20.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mqtt2mqtt@1.2.4~prestart: mqtt2mqtt@1.2.4
6 info lifecycle mqtt2mqtt@1.2.4~start: mqtt2mqtt@1.2.4
7 verbose lifecycle mqtt2mqtt@1.2.4~start: unsafe-perm in lifecycle true
8 verbose lifecycle mqtt2mqtt@1.2.4~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/Mqtt2Mqtt/node_modules/.bin$
9 verbose lifecycle mqtt2mqtt@1.2.4~start: CWD: /root/Mqtt2Mqtt
10 silly lifecycle mqtt2mqtt@1.2.4~start: Args: [ '-c', 'node bin/www' ]
11 silly lifecycle mqtt2mqtt@1.2.4~start: Returned: code: 1  signal: null
12 info lifecycle mqtt2mqtt@1.2.4~start: Failed to exec start script
13 verbose stack Error: mqtt2mqtt@1.2.4 start: `node bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid mqtt2mqtt@1.2.4
15 verbose cwd /root/Mqtt2Mqtt
16 verbose Linux 4.19.62-sunxi
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.20.1
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error mqtt2mqtt@1.2.4 start: `node bin/www`
22 error Exit status 1
23 error Failed at the mqtt2mqtt@1.2.4 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Any idea? 

Thanks!

**Comment by robertsLando** [comment]
Try to disable persistent store and check if it fixes your problem
