### ISSUE TITLE
A passthrough for JSON

### ISSUE THREAD

**Issue by jsponz** [robertsLando/Mqtt2Mqtt#17]
I have some topics sending the info in a JSON. I want to receive the JSON and send it without changes to the MQTT client. A passthrough... 

How should I configure it? 

Thanks!

**Comment by robertsLando** [comment]
YOu could use functions

**Comment by robertsLando** [comment]
YOu could simply create a map and set the Wildecard from and then set the payload to keep original. Then add this map to the client get
