### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by snsiddiqui** [robertsLando/Mqtt2Mqtt#27]
I am running Ubuntu Server 20 on RPi3, getting following error while running npm run build:

npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! mqtt2mqtt@1.2.5 build: `node build/build.js`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the mqtt2mqtt@1.2.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-04-07T22_12_18_180Z-debug.log

Contents of /home/ubuntu/.npm/_logs/2021-04-07T22_12_18_180Z-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle mqtt2mqtt@1.2.5~prebuild: mqtt2mqtt@1.2.5
6 info lifecycle mqtt2mqtt@1.2.5~build: mqtt2mqtt@1.2.5
7 verbose lifecycle mqtt2mqtt@1.2.5~build: unsafe-perm in lifecycle true
8 verbose lifecycle mqtt2mqtt@1.2.5~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/iot/Mqtt2Mqtt/node_modules/.bin:/home/ub>9 verbose lifecycle mqtt2mqtt@1.2.5~build: CWD: /home/ubuntu/iot/Mqtt2Mqtt
10 silly lifecycle mqtt2mqtt@1.2.5~build: Args: [ '-c', 'node build/build.js' ]
11 silly lifecycle mqtt2mqtt@1.2.5~build: Returned: code: 137  signal: null
12 info lifecycle mqtt2mqtt@1.2.5~build: Failed to exec build script
13 verbose stack Error: mqtt2mqtt@1.2.5 build: `node build/build.js`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid mqtt2mqtt@1.2.5
15 verbose cwd /home/ubuntu/iot/Mqtt2Mqtt
16 verbose Linux 5.4.0-1028-raspi
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 137
22 error mqtt2mqtt@1.2.5 build: `node build/build.js`
22 error Exit status 137
23 error Failed at the mqtt2mqtt@1.2.5 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]

**Comment by robertsLando** [comment]
Did you firstly try to run npm install command?

**Comment by snsiddiqui** [comment]
yes, npm install works fine

**Comment by robertsLando** [comment]
The error log you shown me isn't complete as I don't see what is causing it

**Comment by snsiddiqui** [comment]
I ran entire setup again with verbose output, please see below:

$ npm install --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '--verbose' ]
npm info using npm@6.14.4
npm info using node@v10.19.0
npm verb npm-session 4b52a3ae4fcc78be
npm info lifecycle mqtt2mqtt@1.2.5~preinstall: mqtt2mqtt@1.2.5
npm timing stage:loadCurrentTree Completed in 31743ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 318ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 20017ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 23044ms
npm timing stage:loadIdealTree Completed in 53572ms
npm timing stage:generateActionsToTake Completed in 1627ms
npm verb correctMkdir /home/ubuntu/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/ubuntu/.npm/_locks/staging-bd78f5f320d75d87.lock for /home/ubuntu/iot/Mqtt2Mqtt/node_modules/.staging
npm timing audit submit Completed in 1828ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1980ms
npm timing audit body Completed in 216ms
npm timing action:extract Completed in 3448ms
npm timing action:finalize Completed in 837ms
npm timing action:refresh-package-json Completed in 1594ms
npm timing action:preinstall Completed in 11ms
npm timing action:build Completed in 15ms
npm timing action:install Completed in 15ms
npm timing action:postinstall Completed in 19ms
npm verb unlock done using /home/ubuntu/.npm/_locks/staging-bd78f5f320d75d87.lock for /home/ubuntu/iot/Mqtt2Mqtt/node_modules/.staging
npm timing stage:executeActions Completed in 6357ms
npm timing stage:rollbackFailedOptional Completed in 1142ms
npm info linkStuff mqtt2mqtt@1.2.5
npm info lifecycle mqtt2mqtt@1.2.5~install: mqtt2mqtt@1.2.5
npm info lifecycle mqtt2mqtt@1.2.5~postinstall: mqtt2mqtt@1.2.5
npm info lifecycle mqtt2mqtt@1.2.5~prepublish: mqtt2mqtt@1.2.5
npm info lifecycle mqtt2mqtt@1.2.5~prepare: mqtt2mqtt@1.2.5
npm timing stage:runTopLevelLifecycles Completed in 103645ms
npm verb saving []
npm verb shrinkwrap skipping write for package.json because there were no changes.
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm verb shrinkwrap skipping write for package-lock.json because there were no changes.
npm info lifecycle undefined~postshrinkwrap: undefined
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN mqtt2mqtt@1.2.5 No repository field.
npm WARN mqtt2mqtt@1.2.5 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm64

audited 1700 packages in 118.961s
found 1047 vulnerabilities (651 low, 16 moderate, 380 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm verb exit [ 0, true ]
npm timing npm Completed in 134376ms
npm info ok

ubuntu@ubuntu:~/iot/Mqtt2Mqtt$ npm run build --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build', '--verbose' ]
npm info using npm@6.14.4
npm info using node@v10.19.0
npm verb run-script [ 'prebuild', 'build', 'postbuild' ]
npm info lifecycle mqtt2mqtt@1.2.5~prebuild: mqtt2mqtt@1.2.5
npm info lifecycle mqtt2mqtt@1.2.5~build: mqtt2mqtt@1.2.5

> mqtt2mqtt@1.2.5 build /home/ubuntu/iot/Mqtt2Mqtt
> node build/build.js

⠦ building for production...Killed
npm verb lifecycle mqtt2mqtt@1.2.5~build: unsafe-perm in lifecycle true
npm verb lifecycle mqtt2mqtt@1.2.5~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/iot/Mqtt2Mqtt/node_modules/.bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npm verb lifecycle mqtt2mqtt@1.2.5~build: CWD: /home/ubuntu/iot/Mqtt2Mqtt
npm info lifecycle mqtt2mqtt@1.2.5~build: Failed to exec build script
npm verb stack Error: mqtt2mqtt@1.2.5 build: `node build/build.js`
npm verb stack Exit status 137
npm verb stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:198:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:198:13)
npm verb stack     at maybeClose (internal/child_process.js:982:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid mqtt2mqtt@1.2.5
npm verb cwd /home/ubuntu/iot/Mqtt2Mqtt
npm verb Linux 5.4.0-1028-raspi
npm verb argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--verbose"
npm verb node v10.19.0
npm verb npm  v6.14.4
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! mqtt2mqtt@1.2.5 build: `node build/build.js`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the mqtt2mqtt@1.2.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 137, true ]
npm timing npm Completed in 394450ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-04-08T19_52_16_748Z-debug.log

info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build', '--verbose' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle mqtt2mqtt@1.2.5~prebuild: mqtt2mqtt@1.2.5
6 info lifecycle mqtt2mqtt@1.2.5~build: mqtt2mqtt@1.2.5
7 verbose lifecycle mqtt2mqtt@1.2.5~build: unsafe-perm in lifecycle true
8 verbose lifecycle mqtt2mqtt@1.2.5~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/iot/Mqtt2Mqtt/node_modules/.bin:/home/ub>9 verbose lifecycle mqtt2mqtt@1.2.5~build: CWD: /home/ubuntu/iot/Mqtt2Mqtt
10 silly lifecycle mqtt2mqtt@1.2.5~build: Args: [ '-c', 'node build/build.js' ]
11 silly lifecycle mqtt2mqtt@1.2.5~build: Returned: code: 137  signal: null
12 info lifecycle mqtt2mqtt@1.2.5~build: Failed to exec build script
13 verbose stack Error: mqtt2mqtt@1.2.5 build: `node build/build.js`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid mqtt2mqtt@1.2.5
15 verbose cwd /home/ubuntu/iot/Mqtt2Mqtt
16 verbose Linux 5.4.0-1028-raspi
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--verbose"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 137
22 error mqtt2mqtt@1.2.5 build: `node build/build.js`
22 error Exit status 137
23 error Failed at the mqtt2mqtt@1.2.5 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]

**Comment by snsiddiqui** [comment]
I figured it out. It was a node version problem. I updated node to v14.x and build works fine now.
