### ISSUE TITLE
use case: json packets to Home Assistant

### ISSUE THREAD

**Issue by dkebler** [robertsLando/Mqtt2Mqtt#7]
I have an interprocess/device communication system based on json packets.  To integrate with Home Assistant via mqtt required me to use before send hooks on any process needing to send to HA via mqtt that did "conversions/translations". 

I have been thinking of using mcollina's stuff to write a custom broker that could do that.  This would mean I won't have to add that code to every process wanting to talk with HA.  

So I was looking at aedes and he links to your project!!  

I'm just now evaluating it but it looks pretty much what I need.  My topology is simpler than you suggest.  I just need it to translate packets between select clients/topics (no borker2broker).  I can use use it as a generic broker but for particular topics or clients (like HA) I can do the necessary translations at the broker instead of one off in each process (a hassle). 

Thanks for your efforts.  I'll try to provide some feedback as I use/modify it.  

One thing I noticed already was that I'd like to build my mapping/translation functions directly in as opposed to via the interface.  I assume there is some way to easily "register" them into the code/database

**Comment by robertsLando** [comment]
@dkebler Actually every configuration is stored in json files, even map functions, you could modify the code to read them from files
