### ISSUE TITLE
payload map doesn't work 

### ISSUE THREAD

**Issue by rufusgor** [robertsLando/Mqtt2Mqtt#9]
the Value --> JSON (value) function doesn't work

  mqtt2mqtt:M2M-IH Message received on /devices/wb-msw-v3_52/controls/Input Voltage +62ms
  mqtt2mqtt:Broker Client $BROKER PUBLISH on vin: "23.576" +91ms

value property must be "vinin"

**Comment by robertsLando** [comment]
Plese paste here your setting. Export them and from the ui or get them from store folder

**Comment by rufusgor** [comment]
{"clients":[{"name":"IH","host":"127.0.0.1","_ca":"","ca":"","_cert":"","cert":"","_key":"","key":"","port":1883,"reconnectPeriod":1000,"_id":"k84dvvba","mapsSet":["k84dwogi"],"mapsGet":[]}],"values":[],"maps":[{"payloadMap":[],"code":"return {topic: topic, payload: payload}","name":"vin","customTopic":true,"wFrom":"/devices/wb-msw-v3_52/controls/Input Voltage","wTo":"vin","qos":0,"payload":1,"payloadValue":"vinin","_id":"k84dwogi","retain":false}],"broker":{"port":1884},"version":1}

**Comment by robertsLando** [comment]
It seems is working on my instance, have no time to debug it now. Are you able to do some debugging?

**Comment by rufusgor** [comment]
I can try
